import type { LayoutDef } from "./types";

export const LAYOUTS: LayoutDef[] = [
  {
    id: "stripA-3",
    name: "Layout A",
    description: "Classic 3-pose photo strip",
    poses: 3,
    rows: 3,
    cols: 1,
    inchW: 2,
    inchH: 6,
    badge: "TRY IT",
    accent: "from-rose-200 to-rose-100",
    kind: "strip",
    stripTitle: "Takaphotobooth",
  },
  {
    id: "stripB-4",
    name: "Layout B",
    description: "The most popular 4-pose strip",
    poses: 4,
    rows: 4,
    cols: 1,
    inchW: 2,
    inchH: 6,
    badge: "POPULAR",
    accent: "from-amber-100 to-rose-100",
    kind: "strip",
    stripTitle: "Takaphotobooth",
  },
  {
    id: "hearts-4",
    name: "Hearts Filter",
    description: "Romantic strip with heart accents",
    poses: 4,
    rows: 4,
    cols: 1,
    inchW: 2,
    inchH: 6,
    badge: "NEW",
    accent: "from-pink-200 to-rose-200",
    kind: "strip",
    stripTitle: "with love",
  },
  {
    id: "vintage-4",
    name: "Vintage",
    description: "Warm retro 4-pose strip",
    poses: 4,
    rows: 4,
    cols: 1,
    inchW: 2,
    inchH: 6,
    accent: "from-amber-200 to-orange-100",
    kind: "strip",
    stripTitle: "vintage",
  },
  {
    id: "solace-4",
    name: "Solace",
    description: "Minimal premium 4-pose strip",
    poses: 4,
    rows: 4,
    cols: 1,
    inchW: 2,
    inchH: 6,
    badge: "NEW",
    accent: "from-stone-200 to-stone-100",
    kind: "strip",
    stripTitle: "solace",
  },
  {
    id: "grid-6",
    name: "Layout F",
    description: "6 poses in a 3×2 grid",
    poses: 6,
    rows: 3,
    cols: 2,
    inchW: 4,
    inchH: 6,
    accent: "from-violet-200 to-pink-100",
    kind: "grid",
    stripTitle: "Takaphotobooth",
  },
  {
    id: "grid-9",
    name: "Layout G",
    description: "9 poses in a 3×3 grid",
    poses: 9,
    rows: 3,
    cols: 3,
    inchW: 6,
    inchH: 6,
    accent: "from-sky-200 to-violet-100",
    kind: "grid",
    cellAspect: 1,
    stripTitle: "Takaphotobooth",
  },
];

export const getLayout = (id: string | null) =>
  LAYOUTS.find((l) => l.id === id) ?? null;
